/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: sanity/schema.json
export type Seo = {
  _type: "seo";
  metaTitle?: string;
  metaDescription?: string;
  noIndex?: boolean;
};

export type LinkRow = {
  _type: "linkRow";
  links?: Array<
    {
      _key: string;
    } & LabelledLink
  >;
};

export type Link = {
  _type: "link";
  href?: string;
  openInNewTab?: boolean;
};

export type LabelledLink = {
  _type: "labelledLink";
  label?: string;
  href?: string;
};

export type EntryList = {
  _type: "entryList";
  title?: string;
  entries?: Array<{
    meta?: string;
    title?: string;
    description?: string;
    href?: string;
    _type: "entry";
    _key: string;
  }>;
};

export type Detail = {
  _type: "detail";
  label?: string;
  value?: string;
};

export type CodeBlock = {
  _type: "codeBlock";
  language?:
    "text" | "ts" | "tsx" | "js" | "css" | "html" | "json" | "bash" | "groq";
  code?: string;
};

export type WindowText = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal";
  listItem?: never;
  markDefs?: Array<
    {
      _key: string;
    } & Link
  >;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type ArticleText = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h2" | "h3" | "h4" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<
        {
          _key: string;
        } & Link
      >;
      level?: number;
      _type: "block";
      _key: string;
    }
  | {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      caption?: string;
      _type: "image";
      _key: string;
    }
  | ({
      _key: string;
    } & CodeBlock)
  | ({
      _key: string;
    } & LinkRow)
  | ({
      _key: string;
    } & EntryList)
>;

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  publishedAt?: string;
  excerpt?: string;
  body?: ArticleText;
  seo?: Seo;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type DesktopWindow = {
  _id: string;
  _type: "desktopWindow";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  label?: string;
  title?: string;
  slug?: Slug;
  placement?: "home" | "project" | "standalone";
  order?: number;
  text?: WindowText;
  body?: ArticleText;
  cover?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  details?: Array<
    {
      _key: string;
    } & Detail
  >;
  file?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  seo?: Seo;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Settings = {
  _id: string;
  _type: "settings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  email?: string;
  version?: string;
  footerNote?: string;
  social?: Array<
    {
      _key: string;
    } & LabelledLink
  >;
  cornerLinks?: Array<
    {
      _key: string;
    } & LabelledLink
  >;
  navigation?: Array<
    {
      _key: string;
    } & LabelledLink
  >;
  title?: string;
  description?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Seo
  | LinkRow
  | Link
  | LabelledLink
  | EntryList
  | Detail
  | CodeBlock
  | WindowText
  | SanityImageAssetReference
  | ArticleText
  | Post
  | Slug
  | SanityFileAssetReference
  | DesktopWindow
  | SanityImageCrop
  | SanityImageHotspot
  | Settings
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: features/desktop/query.ts
// Variable: SHELL_QUERY
// Query: *[_type == "settings" && _id == "siteSettings"][0]{   name,  title,  description,  email,  version,  footerNote,  social[]{ label, href },  navigation[]{ label, href },  cornerLinks[]{ label, href } }
export type SHELL_QUERY_RESULT = {
  name: string | null;
  title: string | null;
  description: string | null;
  email: string | null;
  version: string | null;
  footerNote: string | null;
  social: Array<{
    label: string | null;
    href: string | null;
  }> | null;
  navigation: Array<{
    label: string | null;
    href: string | null;
  }> | null;
  cornerLinks: Array<{
    label: string | null;
    href: string | null;
  }> | null;
} | null;

// Source: features/desktop/query.ts
// Variable: HOME_WINDOWS_QUERY
// Query: *[_type == "desktopWindow" && placement == "home"] | order(order asc, label asc){      _id,  label,  title,  "slug": slug.current,  placement,  order,  seo,    "body": coalesce(body, text)  }
export type HOME_WINDOWS_QUERY_RESULT = Array<{
  _id: string;
  label: string | null;
  title: string | null;
  slug: string | null;
  placement: "home";
  order: number | null;
  seo: Seo | null;
  body: ArticleText | WindowText | null;
}>;

// Source: features/desktop/query.ts
// Variable: PROJECT_WINDOWS_QUERY
// Query: *[_type == "desktopWindow" && placement == "project" && defined(slug.current)]    | order(order asc, label asc){        _id,  label,  title,  "slug": slug.current,  placement,  order,  seo,      cover{ alt, asset },      "itemCount": count(body[_type == "entryList"][0].entries)    }
export type PROJECT_WINDOWS_QUERY_RESULT = Array<{
  _id: string;
  label: string | null;
  title: string | null;
  slug: string | null;
  placement: "home" | "project" | "standalone" | null;
  order: number | null;
  seo: Seo | null;
  cover: {
    alt: string | null;
    asset: SanityImageAssetReference | null;
  } | null;
  itemCount: number | null;
}>;

// Source: features/desktop/query.ts
// Variable: PROJECT_WINDOW_QUERY
// Query: *[_type == "desktopWindow" && placement == "project" && slug.current == $slug][0]{        _id,  label,  title,  "slug": slug.current,  placement,  order,  seo,  "body": coalesce(body, text),  details[]{ label, value },  cover{ alt, asset },  "file": file.asset->{ url, originalFilename }  }
export type PROJECT_WINDOW_QUERY_RESULT = {
  _id: string;
  label: string | null;
  title: string | null;
  slug: string | null;
  placement: "home" | "project" | "standalone" | null;
  order: number | null;
  seo: Seo | null;
  body: ArticleText | WindowText | null;
  details: Array<{
    label: string | null;
    value: string | null;
  }> | null;
  cover: {
    alt: string | null;
    asset: SanityImageAssetReference | null;
  } | null;
  file: {
    url: string | null;
    originalFilename: string | null;
  } | null;
} | null;

// Source: features/desktop/query.ts
// Variable: STANDALONE_WINDOW_QUERY
// Query: *[_type == "desktopWindow" && placement == "standalone" && slug.current == $slug][0]{        _id,  label,  title,  "slug": slug.current,  placement,  order,  seo,  "body": coalesce(body, text),  details[]{ label, value },  cover{ alt, asset },  "file": file.asset->{ url, originalFilename }  }
export type STANDALONE_WINDOW_QUERY_RESULT = {
  _id: string;
  label: string | null;
  title: string | null;
  slug: string | null;
  placement: "home" | "project" | "standalone" | null;
  order: number | null;
  seo: Seo | null;
  body: ArticleText | WindowText | null;
  details: Array<{
    label: string | null;
    value: string | null;
  }> | null;
  cover: {
    alt: string | null;
    asset: SanityImageAssetReference | null;
  } | null;
  file: {
    url: string | null;
    originalFilename: string | null;
  } | null;
} | null;

// Source: features/desktop/query.ts
// Variable: STANDALONE_SLUGS_QUERY
// Query: *[_type == "desktopWindow" && placement == "standalone" && defined(slug.current)]{    "slug": slug.current  }
export type STANDALONE_SLUGS_QUERY_RESULT = Array<{
  slug: string | null;
}>;

// Source: features/desktop/query.ts
// Variable: PROJECT_SLUGS_QUERY
// Query: *[_type == "desktopWindow" && placement == "project" && defined(slug.current)]{    "slug": slug.current  }
export type PROJECT_SLUGS_QUERY_RESULT = Array<{
  slug: string | null;
}>;

// Source: features/site/query.ts
// Variable: SETTINGS_QUERY
// Query: *[_type == "settings" && _id == "siteSettings"][0]{   name,  title,  description,  email,  version,  footerNote,  social[]{ label, href },  navigation[]{ label, href },  cornerLinks[]{ label, href } }
export type SETTINGS_QUERY_RESULT = {
  name: string | null;
  title: string | null;
  description: string | null;
  email: string | null;
  version: string | null;
  footerNote: string | null;
  social: Array<{
    label: string | null;
    href: string | null;
  }> | null;
  navigation: Array<{
    label: string | null;
    href: string | null;
  }> | null;
  cornerLinks: Array<{
    label: string | null;
    href: string | null;
  }> | null;
} | null;

// Source: features/site/query.ts
// Variable: SITEMAP_QUERY
// Query: {  "pages": *[_type == "desktopWindow" && placement == "standalone"    && defined(slug.current) && seo.noIndex != true]{ "slug": slug.current, _updatedAt },  "windows": *[_type == "desktopWindow" && placement == "project"    && defined(slug.current) && seo.noIndex != true]{ "slug": slug.current, _updatedAt },  "posts": *[_type == "post" && defined(slug.current) && seo.noIndex != true]{    "slug": slug.current,    _updatedAt  }}
export type SITEMAP_QUERY_RESULT = {
  pages: Array<{
    slug: string | null;
    _updatedAt: string;
  }>;
  windows: Array<{
    slug: string | null;
    _updatedAt: string;
  }>;
  posts: Array<{
    slug: string | null;
    _updatedAt: string;
  }>;
};

// Source: features/words/query.ts
// Variable: POSTS_QUERY
// Query: *[_type == "post" && defined(slug.current)] | order(publishedAt desc){   _id,  title,  "slug": slug.current,  excerpt,  publishedAt }
export type POSTS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  excerpt: string | null;
  publishedAt: string | null;
}>;

// Source: features/words/query.ts
// Variable: POST_QUERY
// Query: *[_type == "post" && slug.current == $slug][0]{      _id,  title,  "slug": slug.current,  excerpt,  publishedAt,    body,    seo  }
export type POST_QUERY_RESULT = {
  _id: string;
  title: string | null;
  slug: string | null;
  excerpt: string | null;
  publishedAt: string | null;
  body: ArticleText | null;
  seo: Seo | null;
} | null;

// Source: features/words/query.ts
// Variable: POST_SLUGS_QUERY
// Query: *[_type == "post" && defined(slug.current)]{ "slug": slug.current }
export type POST_SLUGS_QUERY_RESULT = Array<{
  slug: string | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "settings" && _id == "siteSettings"][0]{ \n  name,\n  title,\n  description,\n  email,\n  version,\n  footerNote,\n  social[]{ label, href },\n  navigation[]{ label, href },\n  cornerLinks[]{ label, href }\n }\n':
      SHELL_QUERY_RESULT | SETTINGS_QUERY_RESULT;
    '\n  *[_type == "desktopWindow" && placement == "home"] | order(order asc, label asc){\n    \n  _id,\n  label,\n  title,\n  "slug": slug.current,\n  placement,\n  order,\n  seo\n,\n    "body": coalesce(body, text)\n  }\n': HOME_WINDOWS_QUERY_RESULT;
    '\n  *[_type == "desktopWindow" && placement == "project" && defined(slug.current)]\n    | order(order asc, label asc){\n      \n  _id,\n  label,\n  title,\n  "slug": slug.current,\n  placement,\n  order,\n  seo\n,\n      cover{ alt, asset },\n      "itemCount": count(body[_type == "entryList"][0].entries)\n    }\n': PROJECT_WINDOWS_QUERY_RESULT;
    '\n  *[_type == "desktopWindow" && placement == "project" && slug.current == $slug][0]{\n    \n  \n  _id,\n  label,\n  title,\n  "slug": slug.current,\n  placement,\n  order,\n  seo\n,\n  "body": coalesce(body, text),\n  details[]{ label, value },\n  cover{ alt, asset },\n  "file": file.asset->{ url, originalFilename }\n\n  }\n': PROJECT_WINDOW_QUERY_RESULT;
    '\n  *[_type == "desktopWindow" && placement == "standalone" && slug.current == $slug][0]{\n    \n  \n  _id,\n  label,\n  title,\n  "slug": slug.current,\n  placement,\n  order,\n  seo\n,\n  "body": coalesce(body, text),\n  details[]{ label, value },\n  cover{ alt, asset },\n  "file": file.asset->{ url, originalFilename }\n\n  }\n': STANDALONE_WINDOW_QUERY_RESULT;
    '\n  *[_type == "desktopWindow" && placement == "standalone" && defined(slug.current)]{\n    "slug": slug.current\n  }\n': STANDALONE_SLUGS_QUERY_RESULT;
    '\n  *[_type == "desktopWindow" && placement == "project" && defined(slug.current)]{\n    "slug": slug.current\n  }\n': PROJECT_SLUGS_QUERY_RESULT;
    '{\n  "pages": *[_type == "desktopWindow" && placement == "standalone"\n    && defined(slug.current) && seo.noIndex != true]{ "slug": slug.current, _updatedAt },\n  "windows": *[_type == "desktopWindow" && placement == "project"\n    && defined(slug.current) && seo.noIndex != true]{ "slug": slug.current, _updatedAt },\n  "posts": *[_type == "post" && defined(slug.current) && seo.noIndex != true]{\n    "slug": slug.current,\n    _updatedAt\n  }\n}': SITEMAP_QUERY_RESULT;
    '\n  *[_type == "post" && defined(slug.current)] | order(publishedAt desc){ \n  _id,\n  title,\n  "slug": slug.current,\n  excerpt,\n  publishedAt\n }\n': POSTS_QUERY_RESULT;
    '\n  *[_type == "post" && slug.current == $slug][0]{\n    \n  _id,\n  title,\n  "slug": slug.current,\n  excerpt,\n  publishedAt\n,\n    body,\n    seo\n  }\n': POST_QUERY_RESULT;
    '\n  *[_type == "post" && defined(slug.current)]{ "slug": slug.current }\n': POST_SLUGS_QUERY_RESULT;
  }
}
